Revert "Bind metrics on :: too"
This reverts commit 536c85619f0d0f4daeac120134a3e76c5cbd4703.

Looks like binding metrics on IPv6 (`::`) fails with an error:

socket.gaierror: [Errno -2] Name does not resolve